var x = 4;
document.write("veriable x: " + x + " ,type is: " + typeof x + "<br>");
var y = 4.75;
document.write("veriable y: " + y + " ,type is: " + typeof y + "<br>");
var z = "Hello World";
document.write("veriable z: " + z + " ,type is: " + typeof z + "<br>");
var a = true;
document.write("veriable a: " + a + " ,type is: " + typeof a + "<br>");
var b = null;
document.write("veriable b: " + b + " ,type is: " + typeof b + "<br>");
var c;
document.write("veriable c: " + c + " ,type is: " + typeof c + "<br>");
var d = [1, 2, 3, 4, 5];
document.write("veriable d: " + d + " ,type is: " + typeof d + "<br>");
var e = { name: "John", age: 25 };
document.write("veriable e: " + e + " ,type is: " + typeof e + "<br>");
var f = function () {};
document.write("veriable f: " + f + " ,type is: " + typeof f + "<br>");
var g = new Date();
document.write("veriable g: " + g + " ,type is: " + typeof g + "<br>");
var h = new RegExp("ab+c");
document.write("veriable h: " + h + " ,type is: " + typeof h + "<br>");
var i = new Error("Error");
document.write("veriable i: " + i + " ,type is: " + typeof i + "<br>");
var j = Symbol("id");
document.write("veriable j: " + j + " ,type is: " + typeof j + "<br>");
var k = BigInt(1234567890123456789012345678901234567890);
document.write("veriable k: " + k + " ,type is: " + typeof k + "<br>");
